# Generated by Django 2.2.5 on 2019-09-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='nom_auteur',
        ),
    ]
